FROM node:12.22.6-buster

ENV NODE_ENV=Production
ENV TOKEN_KEY=changeit
ENV PORT=8080
ENV MONGODB_AUTH_ENABLED=1
ENV MONGODB_HOST=localhost
ENV MONGODB_PORT=27017
ENV MONGODB_DBNAME=blchat
ENV MONGODB_USERNAME=root
ENV MONGODB_PASSWORD=changeit
ENV REDIS_HOST=localhost
ENV REDIS_PORT=6379

WORKDIR /app
COPY . .

RUN rm -rf .env

RUN npm install

CMD npm start